import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('owner/player isolation, persistent unlock/revoke, optimistic concurrency',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select '{"is_anonymous":false}'::jsonb$$;grant usage on schema auth to authenticated;grant execute on all functions in schema auth to authenticated;`);
 const sql=(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8')).replace('alter publication supabase_realtime add table public.session_signals;','');
 await db.exec(sql);
 const migration=await readFile(new URL('../supabase/migrations/20260927_tabletop.sql',import.meta.url),'utf8');await db.exec(migration);await db.exec(migration);
 const owner='00000000-0000-0000-0000-000000000001',player='00000000-0000-0000-0000-000000000002',stranger='00000000-0000-0000-0000-000000000003';
 await db.query('insert into auth.users values ($1),($2),($3)',[owner,player,stranger]);
 const as=async id=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[id]);await db.exec('set role authenticated')};
 await as(owner);
 const state={name:'Test',position:{x:.2,y:.3},mapImage:'https://example.org/maps/smoky/station.webp',mapPositions:{privateMap:{x:.5,y:.5}},log:[{text:'Secret log'}],entries:[{id:'public',visible:true,title:'Découverte'},{id:'secret',visible:false,title:'SECRET'}]};
 state.tokens=[{id:'shown',name:'Public',image:'https://example.org/public.webp',mapImage:state.mapImage,x:.3,y:.4,size:.06,color:'#ffffff',visible:true,privateNotes:'NEVER SEND'}, {id:'hidden',name:'SECRET ENEMY',mapImage:state.mapImage,visible:false},{id:'other-scene',name:'NEXT SCENE',mapImage:'https://example.org/next.webp',visible:true}];
 const {rows:[{id}]}=await db.query('select public.create_session($1,$2) as id',['Test',state]);
 const get=async()=> (await db.query('select public.get_session($1) as data',[id])).rows[0].data;
 const gm=await get();assert.equal(gm.role,'gm');assert.equal(gm.state.entries.length,2);
 await as(stranger);await assert.rejects(get,/Accès refusé/);
 await as(player);await db.query('select public.join_session($1)',[gm.invite_code]);
 const p=await get();assert.equal(p.role,'player');assert.deepEqual(p.state.entries.map(e=>e.id),['public']);assert.deepEqual(p.state.log,[]);assert.equal(p.invite_code,undefined);assert.equal(p.state.mapImage,state.mapImage);assert.equal(p.state.mapPositions,undefined);assert.deepEqual(p.state.tokens.map(t=>t.id),['shown']);assert.equal(p.state.tokens[0].privateNotes,undefined);assert.equal(p.state.tokens[0].x,.3);
 await assert.rejects(db.query('select * from public.campaign_sessions'),/permission denied/);
 await assert.rejects(db.query('select public.save_session($1,$2,$3)',[id,state,1]),/réservée/);
 await as(owner);state.tokens[1].visible=true;state.tokens[0].x=.7;state.entries[1].visible=true;await db.query('select public.save_session($1,$2,$3)',[id,state,1]);
 await assert.rejects(db.query('select public.save_session($1,$2,$3)',[id,state,1]),/changé/);
 await as(player);const revealed=await get();assert.equal(revealed.state.entries.length,2);assert.deepEqual(revealed.state.tokens.map(t=>t.id),['shown','hidden']);assert.equal(revealed.state.tokens[0].x,.7);
 await as(owner);state.tokens[1].visible=false;state.entries[1].visible=false;await db.query('select public.save_session($1,$2,$3)',[id,state,2]);
 await as(player);assert.equal((await get()).state.entries.length,1);
 assert.deepEqual((await get()).state.tokens.map(t=>t.id),['shown']);
 await as(owner);state.mapImage='https://example.org/next.webp';await db.query('select public.save_session($1,$2,$3)',[id,state,3]);await as(player);assert.deepEqual((await get()).state.tokens.map(t=>t.id),['other-scene']);
 await db.close();
});
