const {chromium,webkit,devices}=require('playwright');const {spawn}=require('node:child_process');const fs=require('node:fs/promises');const assert=require('node:assert/strict');
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--host','127.0.0.1','--port','4173'],{stdio:'inherit'});
async function main(){for(let i=0;i<60;i++){try{if((await fetch('http://127.0.0.1:4173')).ok)break}catch{}await new Promise(r=>setTimeout(r,200))}await fs.mkdir('test-results',{recursive:true});
 for(const [name,engine] of [['chromium',chromium],['webkit',webkit]]){const browser=await engine.launch();try{
 const context=await browser.newContext({...devices['iPhone 13']});const gm=await context.newPage();const errors=[];gm.on('pageerror',e=>errors.push(e.message));await gm.goto('http://127.0.0.1:4173/#/gm');await gm.getByRole('button',{name:'Terminaux à codes',exact:true}).click();
 await gm.getByLabel('Titre du document',{exact:true}).fill('Journal de contrôle');await gm.getByLabel('Code à donner en jeu',{exact:true}).fill('ABRI-50');await gm.getByLabel('Texte préparé',{exact:true}).fill('Texte de test réservé au MJ.\n'.repeat(40));await gm.getByRole('button',{name:'Enregistrer le terminal',exact:true}).click();await gm.getByRole('button',{name:'Modifier Journal de contrôle',exact:true}).waitFor();
 const player=await context.newPage();player.on('pageerror',e=>errors.push(e.message));await player.goto('http://127.0.0.1:4173/');await player.getByRole('button',{name:'TERMINAL',exact:true}).click();assert.equal(await player.getByText('Journal de contrôle',{exact:true}).count(),0);
 await player.getByLabel('Code d’accès',{exact:true}).fill('NOPE');await player.getByRole('button',{name:'Déverrouiller',exact:true}).click();await player.getByRole('alert').waitFor();assert.equal(await player.locator('.terminal-output').count(),0);
 await player.getByLabel('Code d’accès',{exact:true}).fill('abri-50');await player.getByRole('button',{name:'Déverrouiller',exact:true}).click();await player.getByRole('region',{name:'Document du terminal',exact:true}).waitFor();await player.getByRole('button',{name:'Afficher immédiatement',exact:true}).click();assert.equal(await player.locator('.terminal-text').innerText(),('Texte de test réservé au MJ.\n'.repeat(40)).trim());assert.ok(await player.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await player.screenshot({path:`test-results/terminal-player-${name}.png`,fullPage:true});
 await player.reload();await player.getByRole('button',{name:'TERMINAL',exact:true}).click();await player.getByRole('button',{name:'Journal de contrôle',exact:true}).click();await player.getByRole('region',{name:'Document du terminal',exact:true}).waitFor();
 await gm.getByRole('button',{name:'Refermer l’accès',exact:true}).click();await player.waitForFunction(()=>!document.querySelector('.terminal-output'));assert.equal(await player.getByRole('button',{name:'Journal de contrôle',exact:true}).count(),0);
 await player.getByLabel('Code d’accès',{exact:true}).fill('ABRI-50');await player.getByRole('button',{name:'Déverrouiller',exact:true}).click();await player.getByRole('alert').waitFor();await gm.screenshot({path:`test-results/terminal-gm-${name}.png`,fullPage:true});assert.deepEqual(errors,[]);await context.close();console.log('PASS terminal '+name+': private text, wrong/right code, typing/skip, archive persistence, revoke');
 }finally{await browser.close()}}
}
main().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>server.kill());
