import {useRef,useState} from 'react';
import type {State} from './data';
import {downloadBackup,parseBackup,rollbackKey,saveRollback} from './campaignBackup';
export default function CampaignBackups({state,scope,busy,onRestore}:{state:State;scope:string;busy:boolean;onRestore:(state:State)=>Promise<boolean>}){
 const [candidate,setCandidate]=useState<ReturnType<typeof parseBackup>|null>(null),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[reading,setReading]=useState(false),[message,setMessage]=useState('');const generation=useRef(0);
 const [rollback,setRollback]=useState(()=>{try{return localStorage.getItem(rollbackKey(scope))||''}catch{return ''}});
 async function read(file:File|undefined){const version=++generation.current;setCandidate(null);setConfirmed(false);setError('');setMessage('');if(!file)return;setReading(true);try{if(file.size>1800000)throw Error('Le fichier dépasse 1,8 Mo.');const result=parseBackup(await file.text());if(version===generation.current)setCandidate(result)}catch(e){if(version===generation.current)setError((e as Error).message)}finally{if(version===generation.current)setReading(false)}}
 async function restore(){if(!candidate||!confirmed||busy)return;setError('');try{const checkpoint=saveRollback(state,scope);setRollback(checkpoint);if(await onRestore(candidate.state)){setCandidate(null);setConfirmed(false);setMessage('Campagne restaurée. La copie de secours permet de revenir à l’état précédent.')}else setError('La restauration a échoué. La campagne active n’a pas été remplacée.')}catch(e){setError('Restauration annulée : impossible de préparer la copie de secours. '+(e as Error).message)}}
 return <div className="detail-body backup-panel"><p>La sauvegarde MJ comprend toutes les fiches, les secrets, les pions, les cartes et le suivi du scénario. Les images et les sons restent des liens ; les identifiants de connexion et les notes personnelles du navigateur ne sont pas exportés.</p><button disabled={busy} onClick={()=>{try{downloadBackup(state);setMessage('Fichier de sauvegarde préparé. Enregistre-le dans Fichiers ou dans ton dossier de téléchargements.')}catch(e){setError((e as Error).message)}}}>Télécharger ma campagne</button><label className="backup-file">Choisir une sauvegarde JSON<input type="file" accept=".json,application/json" disabled={busy||reading} onChange={e=>{void read(e.target.files?.[0]);e.target.value=''}}/></label>{reading&&<p role="status">Vérification du fichier…</p>}
 {rollback&&<button disabled={busy||reading} onClick={()=>{try{setCandidate(parseBackup(rollback));setConfirmed(false);setError('');setMessage('Copie de secours chargée dans l’aperçu. Confirme pour revenir à cet état.')}catch(e){setError((e as Error).message)}}}>Revenir à l’état précédent</button>}
 {candidate&&<section className="restore-preview" aria-label="Aperçu de restauration"><h3>{candidate.state.name}</h3><p>{candidate.state.entries.length} fiches · {candidate.state.entries.filter(e=>!e.visible).length} secrètes · {candidate.state.tokens?.length||0} pions</p><p>{candidate.legacy?'Ancien export : il peut être partiel.':'Sauvegarde MJ du '+candidate.date}</p><p>Cette opération remplace « {state.name} » ({state.entries.length} fiches). Les visibilités enregistrées seront rétablies, y compris côté joueuse. Une copie de secours sera conservée sur cet appareil.</p><label className="check"><input type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>Je confirme le remplacement de la campagne active.</label><div className="actions"><button disabled={busy} onClick={()=>{setCandidate(null);setConfirmed(false)}}>Annuler</button><button className="primary" disabled={!confirmed||busy||reading} onClick={()=>void restore()}>Confirmer la restauration</button></div></section>}
 {error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<p className="info">La copie de secours locale est remplacée à chaque restauration. Télécharge aussi tes sauvegardes pour les conserver hors de cet appareil.</p></div>;
}
