export type Kind = 'location'|'person'|'creature'|'item'|'document'|'quest'|'holotape'|'terminal';
export type Entry = {id:string;type:Kind;title:string;summary:string;body:string;tags:string[];visible:boolean;status:string;x?:number;y?:number;audio?:string;image?:string;source?:string;links?:string[]};
export type State = {name:string;entries:Entry[];position:{x:number;y:number};mapImage:string;log:{id:string;text:string;date:string}[]};
export const labels:Record<Kind,string>={location:'Lieux',person:'Personnes',creature:'Faune',item:'Objets',document:'Documents',quest:'Quêtes',holotape:'Holobandes',terminal:'Terminaux'};
const entry=(id:string,type:Kind,title:string,summary:string,body:string,extra:Partial<Entry>={}):Entry=>({id,type,title,summary,body,tags:[],visible:true,status:'Découvert',...extra});
export const initial:State={name:'Les échos du silence',position:{x:.32,y:.55},mapImage:'',log:[],entries:[
entry('abri','location','Abri 17','Votre point de départ. Votre ancien monde.','La porte blindée s’est refermée derrière vous. Pour la première fois, le compteur Geiger ne reste pas silencieux.\n\nLa dernière transmission de l’abri mentionnait une balise à la station relais, au nord-est.',{x:.32,y:.55,tags:['Refuge','Secteur B4']}),
entry('relais','location','Station relais','Un signal faible, mais toujours actif.','Une antenne se découpe au-dessus des pins morts. À intervalles réguliers, elle transmet trois notes et une suite de chiffres. Quelqu’un entretient encore le générateur.',{x:.64,y:.29,tags:['Radio','Secteur D2'],status:'Rumeur'}),
entry('halte','location','La Halte','Un comptoir entre deux mondes.','Des voyageurs ont transformé l’ancienne gare en marché. L’eau est filtrée, les armes restent à l’entrée. Une pancarte annonce : « On fait crédit aux morts. »',{x:.67,y:.68,tags:['Commerce','Secteur D5']}),
entry('station','location','Complexe Hélios','Une installation condamnée.','Le sous-sol contient les archives du programme ÉCHO.',{x:.83,y:.44,visible:false,tags:['Secret MJ']}),
entry('quete','quest','Une voix dans les ruines','Retrouver l’origine de la transmission.','Atteindre la station relais.\nIdentifier la voix sur la fréquence 87.6.\nDécouvrir ce qui est arrivé à la famille Keller.',{status:'En cours',tags:['Quête principale']}),
entry('note','document','À celle qui sortira','Une lettre retrouvée près du sas.','Si tu lis ceci, tu as choisi de sortir.\n\nNe crois pas que le monde est vide parce qu’il ne te répond pas. Trouve la station. Écoute jusqu’au bout. Et, quoi qu’il arrive, n’efface pas la dernière bande.\n\n— M.',{source:'Casier personnel · Abri 17',tags:['Lettre']}),
entry('mara','person','Mara Voss','La gardienne de La Halte.','Ancienne mécanicienne, Mara tient le comptoir avec une patience limitée. Elle accepte les pièces détachées et refuse de parler du complexe Hélios.',{source:'La Halte',tags:['Marchande','Neutre']}),
entry('daniel','person','Daniel Keller','Une voix sur une vieille fréquence.','Ancien technicien du relais. Son nom apparaît dans les registres d’entretien de l’abri. Sa famille aurait quitté la région vingt ans plus tôt.',{visible:false,tags:['Technicien']}),
entry('faune','creature','Chien des friches','Un compagnon prudent et tenace.','Observe de loin avant d’approcher. Réagit aux sifflements courts. Semble connaître le chemin du relais.\n\nDanger observé : faible. Éviter les gestes brusques.',{tags:['Animal','Faible danger']}),
entry('cle','item','Clé du sas extérieur','L’abri vous accompagne encore.','Une petite clé marquée 17. Le métal porte les traces de plusieurs générations de résidents.',{tags:['Clé','Objet de quête']}),
entry('soin','item','Trousse de secours','Un indispensable des Terres désolées.','Bandages, désinfectant et compresses. La date de péremption n’est plus lisible.',{tags:['Soin'],status:'Quantité : 1'}),
entry('bande','holotape','01 — Le dernier matin','Journal de famille · Enregistrement 01','« Papa dit qu’on part demain. Il a mis toutes les photos dans une boîte, sauf celle de la cuisine. Maman ne dit rien. La radio fait encore ce bruit. Je vais laisser le magnétophone ici, au cas où on reviendrait. »\n\n[Transcription originale de démonstration. Ajoutez votre fichier audio depuis la console MJ.]',{source:'Famille Keller · 14 octobre 2287',tags:['Journal familial']}),
entry('terminal','terminal','Registre de l’abri','Poste de sécurité · Terminal 04','Dernière maintenance : 12 octobre 2287.\nÉtat du sas : opérationnel.\nAccès aux archives : limité.',{links:['note'],tags:['Abri 17']})]};
export function newId(){return crypto.randomUUID()}
export function safeUrl(value:string){try{const u=new URL(value);return u.protocol==='https:'||u.protocol==='http:'?u.href:''}catch{return ''}}
