import {useEffect,useRef,useState} from 'react';
import {Radio,Search,Plus,Send,ExternalLink,Play,Check} from 'lucide-react';
import {type Entry,safeUrl} from './data';
export type Tape={id:string;title:string;game:string;series:string;language:string;audio:string;sourceUrl:string};
type Index={updatedAt:string;complete:boolean;items:Tape[]};
export function tapeEntry(t:Tape,visible=false):Entry{return {id:t.id,type:'holotape',title:t.title,summary:t.game+' · '+t.series,body:'Enregistrement référencé sur Les Archives de Vault-Tec. La transcription, lorsqu’elle existe, est consultable sur la page source.',tags:[t.game,t.series,t.language],visible,status:'Reçue',audio:t.audio,source:'Les Archives de Vault-Tec · '+t.game,sourceUrl:t.sourceUrl}}
export default function HolotapeLibrary({entries,onImport,busy}:{entries:Entry[];onImport:(items:Entry[],send:boolean)=>Promise<boolean>;busy:boolean}){
 const [index,setIndex]=useState<Index|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[game,setGame]=useState('all'),[series,setSeries]=useState('all'),[selected,setSelected]=useState<string[]>([]),[preview,setPreview]=useState<Tape|null>(null),[audioError,setAudioError]=useState(''),[limit,setLimit]=useState(24),[retry,setRetry]=useState(0);
 const player=useRef<HTMLAudioElement>(null);
 useEffect(()=>{const ctrl=new AbortController();setError('');fetch(import.meta.env.BASE_URL+'holotapes.json',{signal:ctrl.signal}).then(r=>{if(!r.ok)throw Error('Bibliothèque indisponible');return r.json()}).then((d:Index)=>{if(!Array.isArray(d.items))throw Error('Catalogue invalide');setIndex({...d,items:d.items.filter(t=>safeUrl(t.audio)&&safeUrl(t.sourceUrl))})}).catch(e=>{if(e.name!=='AbortError')setError('Impossible de charger la bibliothèque. Réessayez.')});return()=>ctrl.abort()},[retry]);
 useEffect(()=>setLimit(24),[query,game,series]);
 const items=(index?.items||[]).filter(t=>(game==='all'||t.game===game)&&(series==='all'||t.series===series)&&(t.title+' '+t.series+' '+t.game).toLocaleLowerCase('fr').includes(query.toLocaleLowerCase('fr')));
 const importItems=async(tapes:Tape[],send:boolean)=>{if(await onImport(tapes.map(t=>tapeEntry(t,send)),send))setSelected([])};
 return <main className="catalog-page holo-library"><div className="section-title"><div><span className="eyebrow">ARCHIVES AUDIO / RÉSERVE DU MJ</span><h1>Bibliothèque d’holobandes<span>_</span></h1></div><span className="counter">{index?.items.length||0} ENREGISTREMENTS</span></div>
 <p className="library-intro">Préécoutez les bandes, préparez votre catalogue, puis transmettez les découvertes au joueur. Les fiches de cette bibliothèque ne sont pas révélées automatiquement.</p>
 <div className="filters"><label className="search"><Search size={18}/><input aria-label="Rechercher une holobande" placeholder="Keller, journal, superviseur…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filtrer par jeu" value={game} onChange={e=>{setGame(e.target.value);setSeries('all')}}><option value="all">Tous les jeux</option>{[...new Set(index?.items.map(t=>t.game))].sort().map(g=><option key={g}>{g}</option>)}</select><select aria-label="Filtrer par collection" value={series} onChange={e=>setSeries(e.target.value)}><option value="all">Toutes les collections</option>{[...new Set(index?.items.filter(t=>game==='all'||t.game===game).map(t=>t.series))].sort().map(s=><option key={s}>{s}</option>)}</select></div>
 {error?<p className="error" role="alert">{error} <button onClick={()=>setRetry(retry+1)}>Réessayer</button></p>:!index?<p role="status">Chargement des archives…</p>:<><div className="library-tools"><span>{items.length} résultat(s) · {selected.length} sélection(s)</span><button onClick={()=>setSelected([...new Set([...selected,...items.map(t=>t.id)])])} disabled={!items.length}>Sélectionner les résultats</button><button disabled={!selected.length} onClick={()=>setSelected([])}>Effacer la sélection</button><button className="primary" disabled={!selected.length||busy} onClick={()=>void importItems(index.items.filter(t=>selected.includes(t.id)),false)}><Plus size={17}/>Ajouter la sélection</button></div>
 {preview&&<section className="audio-preview" aria-label="Préécoute MJ"><h2><Radio size={21}/> {preview.title}</h2><audio ref={player} key={preview.audio} controls preload="none" src={preview.audio} onError={()=>setAudioError('Lecture indisponible : le serveur distant ou ce format OGG peut ne pas être compatible avec votre navigateur. Ouvrez le fichier brut ou la page source.')}/>{audioError&&<p className="error" role="alert">{audioError}</p>}<div className="audio-links"><a href={preview.audio} target="_blank" rel="noreferrer">Ouvrir le fichier brut <ExternalLink size={15}/></a><a href={preview.sourceUrl} target="_blank" rel="noreferrer">Page source</a><button onClick={()=>{player.current?.pause();setPreview(null)}}>Fermer la préécoute</button></div></section>}
 <div className="cards">{items.slice(0,limit).map(t=>{const existing=entries.find(e=>e.id===t.id);return <article className="card" key={t.id}><div className="card-top"><Radio size={21}/><span>{t.game}</span><label className="tape-check"><input type="checkbox" aria-label={'Sélectionner '+t.title} checked={selected.includes(t.id)} onChange={e=>setSelected(e.target.checked?[...selected,t.id]:selected.filter(id=>id!==t.id))}/></label></div><h2>{t.title}</h2><div className="tags"><span>{t.series}</span><span>{t.language}</span><span>OGG</span>{existing&&<span>{existing.visible?'Transmise':'Dans le catalogue'}</span>}</div><div className="tape-actions"><button onClick={()=>{player.current?.pause();setAudioError('');setPreview(t)}}><Play size={16}/>Préécouter</button><button disabled={!!existing||busy} onClick={()=>void importItems([t],false)}>{existing?<Check size={16}/>:<Plus size={16}/>} {existing?'Ajoutée':'Ajouter'}</button><button disabled={busy||existing?.visible} onClick={()=>void importItems([t],true)}><Send size={16}/>{existing?.visible?'Transmise':'Envoyer'}</button></div><div className="audio-links"><a href={t.sourceUrl} target="_blank" rel="noreferrer">Source wiki <ExternalLink size={14}/></a><a href={t.audio} target="_blank" rel="noreferrer">Fichier brut</a></div></article>})}</div>{!items.length&&<p className="empty">Aucun enregistrement ne correspond à ces filtres.</p>}{items.length>limit&&<button className="load-more" onClick={()=>setLimit(limit+24)}>Afficher 24 enregistrements supplémentaires</button>}
 <p className="library-credit">Source : <a href="https://fallout-wiki.com/Cat%C3%A9gorie:Enregistrement_d%27holodisque" target="_blank" rel="noreferrer">Les Archives de Vault-Tec</a> · Index du {index.updatedAt.slice(0,10)}{!index.complete?' · Sélection de départ':''}. « Wiki FR » indique la provenance ; la langue de chaque voix reste à vérifier à l’écoute. Audio hébergé par le wiki, sans copie dans ce site. Les droits des enregistrements restent à leurs ayants droit.</p></>}
 </main>
}
