import {useEffect,useState} from 'react';
import {Image,Eye,Plus,Send,Lock,Search} from 'lucide-react';
import {searchText,type Entry} from './data';
export type Illustration={id:string;title:string;type:'person'|'creature';group:string;image:string};
export const illustrationUrl=(path:string)=>new URL(import.meta.env.BASE_URL+path,location.href).href;
function asEntry(item:Illustration):Entry{return {id:item.id,type:item.type,title:item.title,summary:item.type==='person'?'Portrait de personnage':'Illustration de créature',body:'',tags:[],visible:false,status:'Découvert',image:illustrationUrl(item.image)}}
export default function IllustrationLibrary({entries,busy,onImport,onPreview,onHide}:{entries:Entry[];busy:boolean;onImport:(items:Entry[],send:boolean)=>Promise<boolean>;onPreview:(picture:{title:string;image:string})=>void;onHide:(entry:Entry)=>void}){
 const [items,setItems]=useState<Illustration[]|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[query,setQuery]=useState(''),[type,setType]=useState('all'),[group,setGroup]=useState('all');
 useEffect(()=>{const ctrl=new AbortController();setError('');fetch(import.meta.env.BASE_URL+'illustrations.json',{signal:ctrl.signal}).then(async r=>{if(!r.ok)throw Error();const data=await r.json();if(!Array.isArray(data.items)||!data.items.every((i:Illustration)=>typeof i.id==='string'&&typeof i.title==='string'&&typeof i.group==='string'&&['person','creature'].includes(i.type)&&/^illustrations\/smoky\/[a-z-]+\.webp$/.test(i.image)))throw Error();setItems(data.items)}).catch(e=>{if(e.name!=='AbortError')setError('La bibliothèque n’a pas pu être chargée.')});return()=>ctrl.abort()},[retry]);
 const filtered=(items||[]).filter(i=>(type==='all'||type===i.type)&&(group==='all'||group===i.group)&&searchText(i.title).includes(searchText(query)));
 return <main className="catalog-page illustration-library"><div className="section-title"><div><span className="eyebrow">ILLUSTRATIONS / RÉSERVE DU MJ</span><h1>Personnages & créatures<span>_</span></h1></div><span className="counter">{items?.length||0} ILLUSTRATIONS</span></div><p className="library-intro">Une image par rencontre. Prévisualisez sans la révéler, préparez une fiche secrète dans le catalogue, ou révélez-la au joueur. Seuls le nom et l’illustration sont ajoutés, sans informations sur la suite du scénario.</p>
 <div className="filters"><label className="search"><Search size={18}/><input aria-label="Rechercher une illustration" placeholder="Evie, fangeux, Roy…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Type d’illustration" value={type} onChange={e=>setType(e.target.value)}><option value="all">Tous les types</option><option value="person">Personnages</option><option value="creature">Créatures</option></select><select aria-label="Collection d’illustrations" value={group} onChange={e=>setGroup(e.target.value)}><option value="all">Toutes les collections</option>{[...new Set(items?.map(i=>i.group))].map(g=><option key={g}>{g}</option>)}</select></div>
 {error?<p className="error" role="alert">{error}<button onClick={()=>setRetry(retry+1)}>Réessayer</button></p>:!items?<p role="status">Chargement des illustrations…</p>:<><p>{filtered.length} résultat(s)</p><div className="cards illustration-cards">{filtered.map(item=>{const existing=entries.find(e=>e.id===item.id);return <article className="card" key={item.id}><button className="portrait-preview" aria-label={'Prévisualiser '+item.title} onClick={()=>onPreview({title:item.title,image:illustrationUrl(item.image)})}><img loading="lazy" decoding="async" src={illustrationUrl(item.image)} alt={item.title}/></button><div className="card-top"><Image size={18}/><span>{item.group}</span>{existing&&<span className="badge">{existing.visible?'Révélée':'Secrète'}</span>}</div><h2>{item.title}</h2><div className="tape-actions"><button onClick={()=>onPreview({title:item.title,image:illustrationUrl(item.image)})}><Eye size={16}/>Prévisualiser</button><button disabled={busy||!!existing} onClick={()=>void onImport([asEntry(item)],false)}><Plus size={16}/>{existing?'Ajoutée':'Ajouter au catalogue'}</button>{existing?.visible?<button disabled={busy} onClick={()=>onHide(existing)}><Lock size={16}/>Masquer</button>:<button disabled={busy} onClick={()=>void onImport([asEntry(item)],true)}><Send size={16}/>Révéler au joueur</button>}</div></article>})}</div>{!filtered.length&&<p className="empty">Aucune illustration ne correspond à ces filtres.</p>}<p className="library-credit">Mission Smoky Waters · 10 portraits et 6 créatures · Illustrations interprétées à partir du scénario.</p></>}
 </main>
}
