import {useState} from 'react';
import {BookOpen,Check,Eye,Lock,Map,Package} from 'lucide-react';
import sheets from './provided-sheets.json';
import pack from './smoky-pack.json';
import {type State,type Entry,type Kind,type Token} from './data';
import {campaignMaps,mapUrl} from './maps';
import {illustrationUrl} from './IllustrationLibrary';
import {mergeScenario} from './scenario';
const preparedEntries:Entry[]=pack.entries.map(e=>({...e,type:e.type as Kind,image:'image' in e?illustrationUrl('illustrations/smoky/'+e.image+'.webp'):undefined}));
const preparedTokens:Token[]=pack.tokens.map(t=>({...t,image:t.image?illustrationUrl('illustrations/smoky/'+t.image+'.webp'):'',mapImage:mapUrl(campaignMaps.find(m=>m.id===t.mapId)!)}));
export default function ScenarioPrep({state,busy,onSave,onScene}:{state:State;busy:boolean;onSave:(state:State,text:string)=>Promise<boolean>;onScene:(image:string)=>void}){
 const [step,setStep]=useState(pack.notes[0].id),[draft,setDraft]=useState(state.scenario?.notes||'');
 const note=pack.notes.find(n=>n.id===step)!;const scene=campaignMaps.find(m=>m.id===note.mapId)!;
 const progress=state.scenario||{installed:false,completed:[],round:1,effort:20,notes:''};
 const missing=preparedEntries.filter(e=>!state.entries.some(x=>x.id===e.id)).length;
 const update=(patch:Partial<NonNullable<State['scenario']>>)=>onSave({...state,scenario:{...progress,...patch}},'Suivi MJ enregistré');
 const complete=progress.completed.includes(note.id);
 async function toggle(entry:Entry){await onSave({...state,entries:state.entries.map(e=>e.id===entry.id?{...e,visible:!e.visible}:e)},(entry.visible?'Fiche masquée : ':'Fiche révélée : ')+entry.title)}
 return <main className="scenario-page"><div className="section-title"><div><span className="eyebrow">DOSSIER MJ / SCÉNARIO COMPLET</span><h1>Mission Smoky Waters<span>_</span></h1></div><span className="badge"><Lock size={14}/>Notes réservées au MJ</span></div>
 <section className="scenario-install"><BookOpen size={30}/><div><h2>Abri 50 · Équipe 23 · 2192</h2><p>59 fiches • 12 étapes de conduite • 5 cartes • 30 pions. Préparation issue de ton scénario, avec des supports de jeu reformulés et des placements adaptés aux cartes.</p><p>Les nouvelles fiches et les nouveaux pions restent secrets. La carte affichée et tes éléments existants sont conservés. Les portraits déjà importés reçoivent leur description si elle était vide.</p></div><button className="primary" disabled={busy} onClick={()=>void onSave(mergeScenario(state,preparedEntries,preparedTokens),'Mission Smoky Waters préparée en secret')}><Package size={18}/>{progress.installed?'Compléter la préparation':'Préparer dans ma session'}</button><small>{progress.installed?'Préparation installée · '+missing+' fiche(s) manquante(s).':'Le bouton ajoute le dossier à ta session connectée, ou à ta sauvegarde locale en mode démo.'}</small></section>
 <section className="scenario-install"><FileSheets state={state} busy={busy} onSave={onSave}/></section>
 <div className="scenario-layout"><nav aria-label="Déroulé du scénario">{pack.notes.map(n=><button key={n.id} className={n.id===step?'active':''} aria-current={n.id===step?'step':undefined} onClick={()=>setStep(n.id)}>{progress.completed.includes(n.id)&&<Check size={16}/>} {n.title}</button>)}</nav><section className="scenario-step"><div className="scenario-step-head"><h2>{note.title}</h2><button onClick={()=>onScene(mapUrl(scene))}><Map size={16}/>Préparer cette carte</button><button disabled={busy} aria-pressed={complete} onClick={()=>void update({completed:complete?progress.completed.filter(id=>id!==note.id):[...progress.completed,note.id]})}><Check size={16}/>{complete?'Étape terminée':'Marquer comme terminée'}</button></div>
 <div className="read-aloud"><h3>À lire ou à reformuler</h3><p>{note.readAloud}</p></div><h3>Conduite et secrets MJ</h3><p className="scenario-prose">{note.gm}</p><div className="scenario-rules"><h3>Tests et arbitrages</h3><p>{note.tests}</p></div>
 <h3>Fiches à révéler au bon moment</h3><p>Chaque bouton concerne uniquement cette fiche. Les pions se révèlent séparément sur la table.</p><div className="scenario-reveals">{note.reveals.map(id=>{const e=state.entries.find(e=>e.id===id);const template=preparedEntries.find(e=>e.id===id)!;return <div key={id}><span><strong>{e?.title||template.title}</strong><small>{e?e.visible?'Visible dans le Pip-Boy':'Secrète':'À préparer'}</small></span><button disabled={busy||!e} onClick={()=>e&&void toggle(e)}>{e?.visible?<Lock size={16}/>:<Eye size={16}/>} {e?.visible?'Masquer':'Révéler'}</button></div>})}</div>
 </section><aside className="scenario-tracker"><h2>Suivi de partie</h2><p>{progress.completed.length} / {pack.notes.length} étapes cochées</p><label>Tour du combat final<input type="number" min="1" max="99" value={progress.round} disabled={busy} onChange={e=>void update({round:Math.max(1,Math.min(99,Number(e.target.value)||1))})}/></label><p><strong>{3+Math.floor((progress.round-1)/2)} dés de combat</strong> ce tour, selon le repère d’escalade proposé. Pas de lancer automatique.</p><label>Effort restant sur la balise<input type="number" min="0" max="20" value={progress.effort} disabled={busy} onChange={e=>void update({effort:Math.max(0,Math.min(20,Number(e.target.value)||0))})}/></label><p>Compteur manuel : le document donne 20 d’effort mais laisse « Progrès » vide. Complète les paramètres du test avec le Guide du MJ.</p><label>Notes privées de séance<textarea rows={8} value={draft} onChange={e=>setDraft(e.target.value)} onBlur={()=>{if(draft!==progress.notes)void update({notes:draft})}} placeholder="Quantités accordées, tarifs, profils choisis, PV, décisions…"/></label><button disabled={busy||draft===progress.notes} onClick={()=>void update({notes:draft})}>Enregistrer mes notes MJ</button>{draft!==progress.notes&&<p role="status">Notes modifiées, à enregistrer.</p>}<p className="info">Les statistiques officielles, les prétirés et les valeurs manquantes ne sont pas inclus dans le texte fourni. Prévois le livre de base et le Guide du MJ. Aucune holobande n’est imposée par ce scénario.</p></aside></div></main>;
}

function FileSheets({state,busy,onSave}:{state:State;busy:boolean;onSave:(state:State,text:string)=>Promise<boolean>}){
 const missing=sheets.filter(e=>!state.entries.some(x=>x.id===e.id));
 return <><div><h2>Fiches fournies par le MJ</h2><p>Erine Wallace · M.E.D.I.C · Nathan Caldwell. Données transcrites depuis les trois PDF ; les cases vides restent non renseignées.</p></div><button disabled={busy||!missing.length} onClick={()=>void onSave({...state,entries:[...state.entries,...missing.map(e=>({...e,type:'person' as const,visible:false}))]},'Fiches fournies ajoutées en secret')}>{missing.length?'Ajouter les 3 fiches en secret':'Fiches déjà préparées'}</button></>;
}
