import {useEffect,useRef,useState} from 'react';
import {Plus,Minus,Crosshair,Eye,Lock,Trash2,Copy,Send,Users} from 'lucide-react';
import {newId,safeUrl,searchText,type State,type Token} from './data';
import {campaignMaps,mapUrl} from './maps';
import {illustrationUrl,type Illustration} from './IllustrationLibrary';

const clamp=(n:number)=>Math.max(.02,Math.min(.98,n));
export function TokenLayer({tokens,editable=false,busy=false,selected,onSelect,onMove}:{tokens:Token[];editable?:boolean;busy?:boolean;selected?:string;onSelect?:(id:string)=>void;onMove?:(id:string,x:number,y:number)=>Promise<boolean>}){
 return <>{tokens.filter(t=>editable||t.visible).map(t=><TokenPiece key={t.id} token={t} editable={editable} busy={busy} selected={selected===t.id} onSelect={()=>onSelect?.(t.id)} onMove={(x,y)=>onMove?.(t.id,x,y)||Promise.resolve(false)}/>)}</>;
}
function TokenPiece({token:t,editable,busy,selected,onSelect,onMove}:{token:Token;editable:boolean;busy:boolean;selected:boolean;onSelect:()=>void;onMove:(x:number,y:number)=>Promise<boolean>}){
 const [preview,setPreview]=useState<{x:number;y:number}|null>(null);const dragging=useRef(false);
 const point=(e:React.PointerEvent<HTMLButtonElement>)=>{const r=e.currentTarget.parentElement!.getBoundingClientRect();return {x:clamp((e.clientX-r.left)/r.width),y:clamp((e.clientY-r.top)/r.height)}};
 const commit=async(p:{x:number;y:number})=>{setPreview(p);try{await onMove(p.x,p.y)}finally{setPreview(null)}};
 const current=preview||t;
 return <button type="button" className={'table-token '+(editable?'editable ':'')+(!t.visible?'secret ':'')+(selected?'selected':'')} style={{left:current.x*100+'%',top:current.y*100+'%',width:t.size*100+'%',borderColor:t.color}} aria-label={'Pion : '+t.name+(editable&&!t.visible?' (secret)':'')} aria-pressed={editable?selected:undefined} tabIndex={editable?0:-1} onClick={e=>{e.stopPropagation();onSelect()}} onPointerDown={e=>{if(!editable||busy||e.button!==0)return;e.stopPropagation();dragging.current=true;e.currentTarget.setPointerCapture(e.pointerId);onSelect()}} onPointerMove={e=>{if(dragging.current)setPreview(point(e))}} onPointerUp={e=>{if(!dragging.current)return;dragging.current=false;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);void commit(point(e))}} onPointerCancel={()=>{dragging.current=false;setPreview(null)}} onKeyDown={e=>{if(!editable||busy)return;const dirs:Record<string,number[]>={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]};const d=dirs[e.key];if(!d)return;e.preventDefault();void commit({x:clamp(t.x+d[0]*(e.shiftKey?.05:.01)),y:clamp(t.y+d[1]*(e.shiftKey?.05:.01))})}}>
 {safeUrl(t.image)?<img src={safeUrl(t.image)} alt="" draggable={false}/>:<Users aria-hidden="true"/>}<span>{!t.visible&&editable?'◈ ':''}{t.name}</span></button>;
}
export default function Tabletop({state,busy,onSave}:{state:State;busy:boolean;onSave:(state:State,message:string)=>Promise<boolean>}){
 const [scene,setScene]=useState(state.mapImage),[zoom,setZoom]=useState(1),[selected,setSelected]=useState(''),[query,setQuery]=useState('');
 const [library,setLibrary]=useState<Illustration[]>([]),[error,setError]=useState(''),[retry,setRetry]=useState(0),[removed,setRemoved]=useState<Token|null>(null);
 const viewport=useRef<HTMLDivElement>(null);const pan=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 useEffect(()=>{const ctrl=new AbortController();fetch(import.meta.env.BASE_URL+'illustrations.json',{signal:ctrl.signal}).then(async r=>{if(!r.ok)throw Error();const d=await r.json();if(!Array.isArray(d.items))throw Error();setLibrary(d.items)}).catch(e=>{if(e.name!=='AbortError')setError('La réserve d’illustrations n’a pas pu être chargée.')});return()=>ctrl.abort()},[retry]);
 const all=state.tokens||[],tokens=all.filter(t=>t.mapImage===scene),picked=tokens.find(t=>t.id===selected),active=scene===state.mapImage;
 const sceneMap=campaignMaps.find(m=>mapUrl(m)===scene),title=sceneMap?.title||(scene?'Carte personnalisée':'Commonwealth');
 const choices=[{image:'',title:'Commonwealth'},...campaignMaps.map(m=>({image:mapUrl(m),title:m.title})),...(state.mapImage&&!campaignMaps.some(m=>mapUrl(m)===state.mapImage)?[{image:state.mapImage,title:'Carte personnalisée'}]:[])];
 function openScene(image:string){setScene(image);setSelected('');setZoom(1);viewport.current?.scrollTo(0,0)}
 const update=(id:string,patch:Partial<Token>)=>onSave({...state,tokens:all.map(t=>t.id===id?{...t,...patch}:t)},'Pion mis à jour');
 async function add(item?:Illustration,point?:{x:number;y:number}){const t:Token={id:newId(),name:item?.title||'Joueuse',image:item?illustrationUrl(item.image):'',mapImage:scene,x:point?.x??.5,y:point?.y??.5,size:.06,color:item?.type==='creature'?'#f2a275':'#a4ef91',visible:false};if(await onSave({...state,tokens:[...all,t]},'Pion ajouté en secret'))setSelected(t.id)}
 async function publish(){const oldKey=campaignMaps.find(m=>mapUrl(m)===state.mapImage)?.id||state.mapImage||'commonwealth';const key=sceneMap?.id||scene||'commonwealth';await onSave({...state,mapImage:scene,position:state.mapPositions?.[key]||sceneMap?.start||{x:.32,y:.55},mapPositions:{...state.mapPositions,[oldKey]:state.position}},'Scène affichée : '+title)}
 return <main className="table-page"><div className="section-title"><div><span className="eyebrow">TABLE VIRTUELLE / MISSION SMOKY WATERS</span><h1>Table de jeu<span>_</span></h1></div><span className="badge">{active?'SCÈNE AFFICHÉE AU JOUEUR':'PRÉPARATION PRIVÉE'}</span></div>
 <div className="scene-strip" aria-label="Scènes de la campagne">{choices.map(m=><button disabled={busy} key={m.image} className={scene===m.image?'active':''} aria-pressed={scene===m.image} onClick={()=>openScene(m.image)}>{m.title}{state.mapImage===m.image?' • En jeu':''}</button>)}</div>
 <div className="table-layout"><aside className="token-library"><h2>Réserve de pions</h2><p>Glissez une illustration sur la carte ou touchez Ajouter. Les nouveaux pions sont secrets.</p><button disabled={busy} onClick={()=>void add()}><Plus size={16}/>Ajouter un pion joueur</button><label>Rechercher un pion<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Mouche, Evie…"/></label>{error?<p role="alert">{error}<button onClick={()=>{setError('');setRetry(retry+1)}}>Réessayer</button></p>:<div className="token-palette">{library.filter(i=>searchText(i.title).includes(searchText(query))).map(i=><div key={i.id} draggable={!busy} onDragStart={e=>e.dataTransfer.setData('application/pipboy-illustration',i.id)}><img loading="lazy" src={illustrationUrl(i.image)} alt=""/><span>{i.title}</span><button disabled={busy} aria-label={'Ajouter '+i.title} onClick={()=>void add(i)}><Plus size={16}/></button></div>)}</div>}</aside>
 <section className="table-stage"><div className="table-tools"><strong>{title}</strong><div><button aria-label="Réduire la table" onClick={()=>setZoom(z=>Math.max(1,z-.5))}><Minus size={17}/></button><span>{zoom*100}%</span><button aria-label="Agrandir la table" onClick={()=>setZoom(z=>Math.min(4,z+.5))}><Plus size={17}/></button><button aria-label="Recentrer la table" onClick={()=>{setZoom(1);viewport.current?.scrollTo(0,0)}}><Crosshair size={17}/></button></div></div>
 <div className="table-viewport" ref={viewport} onPointerDown={e=>{if(e.pointerType!=='mouse'||e.button!==0||(e.target as HTMLElement).closest('button'))return;pan.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId);e.preventDefault()}} onPointerMove={e=>{if(!pan.current)return;e.currentTarget.scrollLeft=pan.current.left-(e.clientX-pan.current.x);e.currentTarget.scrollTop=pan.current.top-(e.clientY-pan.current.y)}} onPointerUp={e=>{pan.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>{pan.current=null}}>
 <div className="table-canvas" style={{width:zoom*100+'%'}} onDragOver={e=>{e.preventDefault();e.dataTransfer.dropEffect='copy'}} onDrop={e=>{e.preventDefault();if(busy)return;const item=library.find(i=>i.id===e.dataTransfer.getData('application/pipboy-illustration'));if(!item)return;const r=e.currentTarget.getBoundingClientRect();void add(item,{x:clamp((e.clientX-r.left)/r.width),y:clamp((e.clientY-r.top)/r.height)})}}><img className="table-background" src={safeUrl(scene)||import.meta.env.BASE_URL+'maps/commonwealth.jpg'} alt={'Plateau : '+title} draggable={false}/><TokenLayer tokens={tokens} editable busy={busy} selected={selected} onSelect={setSelected} onMove={(id,x,y)=>update(id,{x,y})}/></div></div>
 <div className="table-status"><span>{tokens.length} pion(s) · {tokens.filter(t=>t.visible).length} révélé(s)</span><button className="primary" disabled={busy||active} onClick={()=>void publish()}><Send size={16}/>{active?'Affichée sur le Pip-Boy':'Afficher cette scène'}</button></div><p className="table-help">Glissez le fond pour vous déplacer. Sur téléphone, faites défiler la carte. Déplacez les pions au doigt ou avec les flèches du clavier.</p></section>
 <aside className="token-inspector"><h2>{picked?'Pion sélectionné':'Préparer la rencontre'}</h2>{picked?<div key={picked.id}><label>Nom du pion<input maxLength={100} defaultValue={picked.name} disabled={busy} onBlur={e=>{const name=e.target.value.trim()||picked.name;e.target.value=name;if(name!==picked.name)void update(picked.id,{name})}}/></label><label>Taille du pion<select value={picked.size} disabled={busy} onChange={e=>void update(picked.id,{size:Number(e.target.value)})}><option value={.04}>Petit</option><option value={.06}>Moyen</option><option value={.09}>Grand</option><option value={.12}>Très grand</option></select></label><p>{picked.visible?'Visible sur cette scène lorsqu’elle est affichée.':'Secret : visible uniquement dans la console MJ.'}</p><button disabled={busy} onClick={()=>void update(picked.id,{visible:!picked.visible})}>{picked.visible?<Lock size={16}/>:<Eye size={16}/>} {picked.visible?'Masquer le pion':'Révéler le pion'}</button><button disabled={busy} onClick={async()=>{const copy={...picked,id:newId(),x:clamp(picked.x+.06),y:clamp(picked.y+.06),visible:false};if(await onSave({...state,tokens:[...all,copy]},'Pion dupliqué en secret'))setSelected(copy.id)}}><Copy size={16}/>Dupliquer en secret</button><button disabled={busy} onClick={async()=>{if(await onSave({...state,tokens:all.filter(t=>t.id!==picked.id)},'Pion retiré')){setRemoved(picked);setSelected('')}}}><Trash2 size={16}/>Retirer le pion</button></div>:<p>Choisissez une scène et ajoutez vos personnages ou créatures. Sélectionnez un pion pour le régler ou le révéler.</p>}{removed&&<button disabled={busy} onClick={async()=>{if(await onSave({...state,tokens:[...all,removed]},'Pion restauré'))setRemoved(null)}}>Annuler la suppression</button>}<div className="scene-token-list"><h3>Pions de la scène</h3>{tokens.map(t=><button key={t.id} onClick={()=>setSelected(t.id)} aria-pressed={selected===t.id}>{t.visible?<Eye size={14}/>:<Lock size={14}/>} {t.name}</button>)}{!tokens.length&&<p>Aucun pion pour le moment.</p>}</div></aside></div></main>;
}
