import {useEffect,useState,useRef} from 'react';
import type {State,Entry,TerminalRecord} from './data';
import {newId} from './data';
import {normalizeCode} from './terminal';
import {rpc} from './store';
const blank=():TerminalRecord=>({id:newId(),title:'',body:'',code:'',enabled:true});
export default function TerminalConsole({state,gm,busy,session,onSave,onUnlock}:{state:State;gm:boolean;busy:boolean;session:string;onSave:(s:State,text:string)=>Promise<boolean>;onUnlock:(code:string)=>Promise<Entry>}){
 const [draft,setDraft]=useState<TerminalRecord>(blank),[code,setCode]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState(false),[active,setActive]=useState<Entry|null>(null),[count,setCount]=useState(0),[ready,setReady]=useState(!session),[checking,setChecking]=useState(false),[setup,setSetup]=useState(''),[notice,setNotice]=useState('');
 const output=useRef<HTMLElement>(null);
 useEffect(()=>{if(active){output.current?.scrollIntoView({block:"start",behavior:"instant"});output.current?.focus()}},[active?.id]);
 const records=state.terminals||[],archives=state.entries.filter(e=>e.type==='terminal'&&e.visible);
 async function check(){if(!session)return;setChecking(true);try{setReady(await rpc<boolean>('terminal_status',{p_id:session}));setNotice('')}catch{setReady(false)}finally{setChecking(false)}}
 useEffect(()=>{void check()},[session]);
 useEffect(()=>{if(!active)return;const current=archives.find(e=>e.id===active.id);if(!current){setActive(null);return}if(current.body!==active.body||current.title!==active.title)setActive(current)},[state.entries]);
 useEffect(()=>{if(!active)return;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){setCount(active.body.length);return}setCount(0);const timer=setInterval(()=>setCount(n=>{if(n>=active.body.length){clearInterval(timer);return n}return Math.min(active.body.length,n+4)}),20);return()=>clearInterval(timer)},[active?.id,active?.body]);
 async function saveDraft(e:React.FormEvent){e.preventDefault();setError('');const value={...draft,title:draft.title.trim(),body:draft.body.trim(),code:normalizeCode(draft.code)};if(!value.title||!value.body||!/^[A-Z0-9-]{4,32}$/.test(value.code)){setError('Titre, texte et code de 4 à 32 caractères requis (A–Z, 0–9, tiret).');return}if(records.some(t=>t.id!==value.id&&t.code===value.code)){setError('Ce code est déjà utilisé.');return}setPending(true);try{if(await onSave({...state,terminals:[...records.filter(t=>t.id!==value.id),value]},'Texte de terminal préparé en secret')){setDraft(blank());setNotice('Texte enregistré. Donne le code en jeu au moment choisi.')}}finally{setPending(false)}}
 async function unlock(e:React.FormEvent){e.preventDefault();setPending(true);setError('');try{const entry=await onUnlock(normalizeCode(code));setActive(entry);setCode('')}catch(e){setError((e as Error).message)}finally{setPending(false)}}
 const disabled=busy||pending;
 return <main className="terminal-page"><div className="section-title"><div><span className="eyebrow">ROBCO · ACCÈS AUX ARCHIVES</span><h1>{gm?'Préparer les terminaux':'Terminal'}<span>_</span></h1></div></div>
 {gm&&<><p>Prépare un texte et son code. Rien n’est transmis avant la saisie du bon code. Le document déverrouillé rejoint les archives de tous les joueurs de cette session.</p>{session&&!ready&&<section className="terminal-setup"><h2>Activer les codes dans Supabase</h2><p>Une mise à jour de la base est nécessaire une seule fois. Tu peux déjà préparer tes textes.</p><button disabled={checking} onClick={()=>void check()}>{checking?'Vérification…':'Vérifier l’activation'}</button><button onClick={async()=>{try{const r=await fetch(import.meta.env.BASE_URL+'setup/terminals.sql');if(!r.ok)throw Error();const sql=await r.text();setSetup(sql);try{await navigator.clipboard.writeText(sql);setNotice('Script copié. Colle-le dans SQL Editor puis lance Run.')}catch{setNotice('Sélectionne et copie le script ci-dessous.')}}catch{setError('Impossible de charger le script. Réessaie.')}}}>Copier le script d’activation</button><a href="https://supabase.com/dashboard/project/xkoybrcmhmfvfmfwqphu/sql/new" target="_blank" rel="noreferrer">Ouvrir SQL Editor</a>{setup&&<textarea aria-label="Script d’activation Supabase" readOnly value={setup} onFocus={e=>e.target.select()}/>}</section>}
 <div className="terminal-prep"><form onSubmit={saveDraft}><h2>{records.some(t=>t.id===draft.id)?'Modifier un texte':'Nouveau texte'}</h2><label>Titre du document<input required maxLength={140} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Code à donner en jeu<input required minLength={4} maxLength={32} autoCapitalize="characters" autoComplete="off" spellCheck={false} value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value.toUpperCase()})}/></label><label>Texte préparé<textarea required rows={10} maxLength={50000} value={draft.body} onChange={e=>setDraft({...draft,body:e.target.value})}/></label><label className="check"><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/>Code actif</label><button className="primary" disabled={disabled}>Enregistrer le terminal</button>{records.some(t=>t.id===draft.id)&&<button type="button" onClick={()=>setDraft(blank())}>Nouveau texte</button>}<p>Modifier le texte préparé ne remplace pas une archive déjà transmise : elle sera actualisée à la prochaine saisie du code.</p></form><section><h2>Textes préparés ({records.length})</h2>{records.map(t=><article key={t.id}><h3>{t.title}</h3><p>Code : <strong>{t.code}</strong> · {t.enabled?'Actif':'Désactivé'}</p><button disabled={disabled} onClick={()=>{setDraft({...t});setError('')}}>Modifier {t.title}</button><button disabled={disabled} onClick={()=>void onSave({...state,terminals:records.map(x=>x.id===t.id?{...x,enabled:!x.enabled}:x)},'Code de terminal '+(t.enabled?'désactivé':'activé'))}>{t.enabled?'Désactiver le code':'Activer le code'}</button>{archives.some(e=>e.id==='terminal-note-'+t.id)&&<button disabled={disabled} onClick={()=>void onSave({...state,terminals:records.map(x=>x.id===t.id?{...x,enabled:false}:x),entries:state.entries.map(e=>e.id==='terminal-note-'+t.id?{...e,visible:false}:e)},'Code désactivé et archive retirée')}>Refermer l’accès</button>}</article>)}{!records.length&&<p>Aucun texte préparé. Aucun contenu de démonstration.</p>}</section></div></>}
 {!gm&&<form className="terminal-access" onSubmit={unlock}><label>Code d’accès<input aria-label="Code d’accès" value={code} required minLength={4} maxLength={32} autoComplete="off" autoCapitalize="characters" spellCheck={false} onChange={e=>setCode(e.target.value.toUpperCase())}/></label><button className="primary" disabled={disabled}>{pending?'Vérification…':'Déverrouiller'}</button><p>Saisis le code donné par le MJ ou découvert pendant la partie.</p></form>}
 {error&&<p className="error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <section className="terminal-archives"><h2>Archives déverrouillées</h2>{archives.map(e=><button key={e.id} onClick={()=>setActive(e)}>{e.title}</button>)}{!archives.length&&<p>Aucune entrée déverrouillée.</p>}</section>
 {active&&<section ref={output} tabIndex={-1} className="terminal-output" aria-label="Document du terminal"><div role="status">ACCÈS AUTORISÉ · DOCUMENT ARCHIVÉ</div><h2>{active.title}</h2><div className="terminal-text" aria-hidden="true">{active.body.slice(0,count)}{count<active.body.length&&<span className="terminal-cursor">▌</span>}</div><p className="terminal-sr">{active.body}</p>{count<active.body.length&&<button onClick={()=>setCount(active.body.length)}>Afficher immédiatement</button>}<button onClick={()=>setActive(null)}>Fermer le document</button></section>}
 </main>;
}
